server: 
  port: 9004
logging: 
  #file: demo.log
  pattern: 
    console: "%d - %msg%n"
  level: 
    org.springframework.web: debug
    com.lxs: debug
security: 
  oauth2: 
    resource: 
      jwt: 
        key-uri: http://localhost:9098/oauth/token_key #如果使用JWT，可以获取公钥用于 token 的验签
spring: 
  servlet: 
    multipart: 
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
fdfs: 
  #链接超时
  connect-timeout: 60
  #读取时间
  so-timeout: 60
  #生成缩略图参数
  thumb-image: 
    width: 150
    height: 150
  tracker-list: 192.168.135.132:22122
